#!/usr/bin/env python3
# Writes ops.txt, the op script mkfixture.c and xformat_test.odin both run:
# a volume's history of directories, files and links made, written (inline,
# in blocks, sparse), truncated, renamed, removed and orphaned, in two
# branches, with commits, snapshots, forks, deletions, a rollback and log
# compressions. It keeps a model of each branch, so most ops are valid, and
# adds some that are refused (a name taken, a directory not empty, a path not
# there), so refusals are compared too. Deterministic: run it again and the
# script is the same.
import copy
import random

r = random.Random(20261004)
out = []
now = 1_700_000_000_000_000_000


def op(*w):
    out.append(" ".join(str(x) for x in w))


class Branch:
    def __init__(self):
        self.dirs = {""}
        self.files = set()
        self.links = set()

    def children(self, d):
        pfx = d + "/"
        return [p for p in self.dirs | self.files | self.links if p.startswith(pfx)]


op("# Generated by gen-ops.py; see mkfixture.c for the language.")
op("time", now)
op("format", 260, 4, 2, "store", "cfg", "home", "adm")
op("users", "vectra")
live = {"home": Branch(), "cfg": Branch()}
committed = copy.deepcopy(live)
snaps = {}  # label -> (branch, model)
forks = []
serial = 0


def commit():
    global committed
    op("commit")
    committed = copy.deepcopy(live)


def pick(s):
    return r.choice(sorted(s)) if s else None


for step in range(360):
    now += r.randrange(1, 5_000_000_000)
    if r.random() < 0.2:
        op("time", now)
    name = r.choice(["home", "home", "cfg"])
    b = live[name]
    k = r.random()
    refuse = r.random() < 0.08
    if k < 0.10:
        p = "%s/d%d" % (pick(b.dirs), r.randrange(12))
        op("mkdir", name, p, "%o" % r.choice([0o755, 0o700, 0o775]))
        if p not in b.dirs | b.files | b.links:
            b.dirs.add(p)
    elif k < 0.24:
        p = "%s/f%d" % (pick(b.dirs), r.randrange(20))
        op("create", name, p, "%o" % r.choice([0o644, 0o600, 0o755]))
        if p not in b.dirs | b.files | b.links:
            b.files.add(p)
    elif k < 0.28:
        p = "%s/l%d" % (pick(b.dirs), r.randrange(10))
        op("symlink", name, p, r.choice(["../x", "/bin/rc", "f1", "a/very/long/target/" * 6]))
        if p not in b.dirs | b.files | b.links:
            b.links.add(p)
    elif k < 0.52 and b.files:
        big = r.random() < 0.3
        off = r.choice([0, 0, r.randrange(600), r.randrange(60000)]) if big else r.randrange(700)
        n = r.randrange(16384, 40000) if big else r.randrange(1, 600)
        p = pick(b.files) if not refuse else "/no/such/file"
        op("write", name, p, off, n, r.randrange(1000))
    elif k < 0.57 and b.files:
        op("truncate", name, pick(b.files), r.choice([0, 3, 511, 512, 20000, r.randrange(70000)]))
    elif k < 0.60 and b.files:
        op("chmod", name, pick(b.files), "%o" % r.choice([0o600, 0o640, 0o4755]))
    elif k < 0.66:
        if refuse and len(b.dirs) > 1:
            d = pick(b.dirs - {""})
            op("remove", name, d)  # refused if it is not empty
            if not b.children(d):
                b.dirs.discard(d)
        elif b.files or b.links:
            p = pick(b.files | b.links)
            op("remove", name, p)
            b.files.discard(p)
            b.links.discard(p)
    elif k < 0.71 and b.files:
        p = pick(b.files)
        q = "%s/m%d" % (pick(b.dirs), r.randrange(12))
        op("rename", name, p, q)
        if q in b.dirs:
            pass  # refused: a file cannot replace a directory
        elif q != p:
            b.files.discard(p)
            b.links.discard(q)
            b.files.add(q)
    elif k < 0.73 and b.files:
        p = pick(b.files)
        op("orphan", name, p)
        b.files.discard(p)
    elif k < 0.84:
        commit()
        if r.random() < 0.35:
            op("compress", r.randrange(4))
    elif k < 0.89:
        serial += 1
        s = "%s@%d" % (name, serial)
        op("snap", name, s)
        snaps[s] = (name, copy.deepcopy(committed[name]))
    elif k < 0.91 and snaps and len(forks) < 2:
        serial += 1
        f = "work%d" % serial
        op("fork", pick(snaps.keys()), f)
        forks.append(f)
    elif k < 0.93 and len(snaps) > 2:
        s = pick(snaps.keys())
        op("del", s)
        del snaps[s]
    elif k < 0.94 and forks:
        commit()
        f = forks.pop(0)
        op("close", f)
        op("del", f)
    elif k < 0.95 and snaps and step < 300:
        commit()
        s = pick([s for s in snaps if snaps[s][0] == name] or [None])
        if s:
            op("rollback", name, s)
            live[name] = copy.deepcopy(snaps[s][1])
            committed[name] = copy.deepcopy(snaps[s][1])
    elif k < 0.96:
        op("reapall", name)
commit()
open("ops.txt", "w").write("\n".join(out) + "\n")
