// abigen: expands abi/vx/*.def into abi/vx/abi_gen.odin, and each format's
// key table (NAME.def of KEY lines, beside its parser) into NAME_keys_gen.odin.
// The ./build wrapper runs it before compiling anything, the build tool
// included (which reaches abi:vx through lib/tar), whenever a table is newer
// than abi_gen.odin or a table's output is missing.
package abigen

import "core:fmt"
import "core:os"
import "core:strconv"
import "core:strings"

// One table, one truth: the ABI's lists live in abi/vx/*.def, the formats'
// keys in their .def tables, and this file expands them into Odin (ADR-0003).

Def_Entry :: struct {
	name:  string,
	value: string, // empty when the table's order gives the value
	line:  int,
}

// Reads the entries of one X-macro table: lines of the form MACRO(NAME) or
// MACRO(NAME, VALUE), with // comments and blank lines ignored.
parse_def :: proc(path, macro: string) -> (entries: [dynamic]Def_Entry, ok: bool) {
	data, err := os.read_entire_file(path, context.temp_allocator)
	if err != nil {
		fmt.eprintfln("build: cannot read %s: %v", path, err)
		return nil, false
	}
	entries = make([dynamic]Def_Entry, context.temp_allocator)
	text := string(data)
	line_no := 0
	for raw in strings.split_lines_iterator(&text) {
		line_no += 1
		line := raw
		if i := strings.index(line, "//"); i >= 0 {
			line = line[:i]
		}
		line = strings.trim_space(line)
		if line == "" {
			continue
		}
		if !strings.has_prefix(line, macro) || !strings.has_suffix(line, ")") || line[len(macro)] != '(' {
			fmt.eprintfln("%s:%d: expected %s(...)", path, line_no, macro)
			return nil, false
		}
		args := strings.split(line[len(macro) + 1:len(line) - 1], ",", context.temp_allocator)
		e := Def_Entry{name = strings.trim_space(args[0]), line = line_no}
		if e.name == "" {
			fmt.eprintfln("%s:%d: %s() has no name", path, line_no, macro)
			return nil, false
		}
		switch len(args) {
		case 1:
		case 2:
			e.value = strings.trim_space(args[1])
			if _, vok := strconv.parse_i64(e.value); !vok {
				fmt.eprintfln("%s:%d: value %q is not an integer", path, line_no, e.value)
				return nil, false
			}
		case:
			fmt.eprintfln("%s:%d: too many arguments", path, line_no)
			return nil, false
		}
		append(&entries, e)
	}
	return entries, true
}

// Odin's naming for a C table name: task_create -> Task_Create, ERR_NIL -> Err_Nil.
ada_case :: proc(name: string) -> string {
	return strings.to_ada_case(strings.to_lower(name, context.temp_allocator), context.temp_allocator)
}

// Generates abi/vx/abi_gen.odin from the three tables.
gen_abi :: proc(root: string) -> bool {
	syscalls := parse_def(fmt.tprintf("%s/abi/vx/syscalls.def", root), "VX_SYSCALL") or_return
	rights := parse_def(fmt.tprintf("%s/abi/vx/rights.def", root), "VX_RIGHT") or_return
	status_path := fmt.tprintf("%s/abi/vx/status.def", root)
	statuses := parse_def(status_path, "VX_STATUS") or_return

	b := strings.builder_make(context.temp_allocator)
	w := &b
	fmt.sbprintln(w, "// Generated by ./build from abi/vx/*.def. Do not edit.")
	fmt.sbprintln(w)
	fmt.sbprintln(w, "package vx")
	fmt.sbprintln(w)

	fmt.sbprintln(w, "// The syscall surface; the order gives the number.")
	fmt.sbprintln(w, "Syscall :: enum u32 {")
	for e in syscalls {
		fmt.sbprintfln(w, "\t%s,", ada_case(e.name))
	}
	fmt.sbprintln(w, "}")
	fmt.sbprintln(w)
	fmt.sbprintfln(w, "SYSCALL_COUNT :: %d", len(syscalls))
	fmt.sbprintln(w)
	fmt.sbprintln(w, "SYSCALL_NAMES := [Syscall]string{")
	for e in syscalls {
		fmt.sbprintfln(w, "\t.%s = %q,", ada_case(e.name), e.name)
	}
	fmt.sbprintln(w, "}")
	fmt.sbprintln(w)

	if len(rights) > 31 {
		// Bit 31 is VX_RIGHTS_SAME, handle_dup's "the rights the handle has".
		fmt.eprintfln("build: %d rights; at most 31 fit below VX_RIGHTS_SAME", len(rights))
		return false
	}
	fmt.sbprintln(w, "// Handle rights; the order gives the bit number.")
	fmt.sbprintln(w, "Right :: enum u32 {")
	for e in rights {
		fmt.sbprintfln(w, "\t%s,", ada_case(e.name))
	}
	fmt.sbprintln(w, "}")
	fmt.sbprintln(w)
	fmt.sbprintln(w, "Rights :: distinct bit_set[Right; u32]")
	fmt.sbprintln(w)

	fmt.sbprintln(w, "// Status codes: OK is zero and the only success; every error is negative.")
	fmt.sbprintln(w, "Status :: enum i32 {")
	for e in statuses {
		if e.value == "" {
			fmt.eprintfln("%s:%d: %s has no value", status_path, e.line, e.name)
			return false
		}
		fmt.sbprintfln(w, "\t%s = %s,", ada_case(e.name), e.value)
	}
	fmt.sbprintln(w, "}")

	out := fmt.tprintf("%s/abi/vx/abi_gen.odin", root)
	if err := os.write_entire_file(out, b.buf[:]); err != nil {
		fmt.eprintfln("build: cannot write %s: %v", out, err)
		return false
	}
	fmt.printfln("build: %s (%d syscalls, %d rights, %d statuses)", out, len(syscalls), len(rights), len(statuses))
	return true
}

// --- The formats' key tables (upstream's M6 step 6b) ---
//
// Each ndb format with keys of its own keeps them in a .def table of
// KEY("scope", "key") lines beside the package that parses it (lib/slots,
// lib/store, servers/svcd, servers/devmgr). Each table NAME.def becomes
// NAME_keys_gen.odin in that package: NAME_KEYS, the keys in the table's
// order, which the parser hands to ndb.unknown_key. ./build man --check holds
// the format's page to the same table (tools/build/man.odin).

// The packages a key table may sit beside: one directory level under each.
KEY_ROOTS :: [?]string{"lib", "servers", "cmd", "drivers"}

// The next "..." in s, and what follows it.
@(private="file")
quoted :: proc(s: string) -> (text, rest: string, ok: bool) {
	q := strings.index_byte(s, '"')
	if q < 0 {
		return "", s, false
	}
	e := strings.index_byte(s[q + 1:], '"')
	if e < 0 {
		return "", s, false
	}
	return s[q + 1:][:e], s[q + 1 + e + 1:], true
}

// A table's keys, from its KEY("scope", "key") lines; // comments and blank
// lines are ignored. is_table is false for a .def of another kind.
parse_keys :: proc(path: string) -> (keys: [dynamic]string, is_table, ok: bool) {
	data, err := os.read_entire_file(path, context.temp_allocator)
	if err != nil {
		fmt.eprintfln("build: cannot read %s: %v", path, err)
		return nil, false, false
	}
	keys = make([dynamic]string, context.temp_allocator)
	text := string(data)
	line_no := 0
	for raw in strings.split_lines_iterator(&text) {
		line_no += 1
		line := strings.trim_space(raw)
		if !strings.has_prefix(line, "KEY(") {
			continue
		}
		is_table = true
		_, after_scope, scope_ok := quoted(line[4:])
		key, after_key, key_ok := quoted(after_scope)
		if !scope_ok || !key_ok || key == "" || strings.trim_space(after_key) != ")" {
			fmt.eprintfln("%s:%d: expected KEY(\"scope\", \"key\")", path, line_no)
			return nil, true, false
		}
		append(&keys, key)
	}
	return keys, is_table, true
}

// The package clause of the Odin files in dir.
@(private="file")
package_of :: proc(dir: string, files: []os.File_Info) -> (name: string, ok: bool) {
	for f in files {
		if f.type != .Regular || !strings.has_suffix(f.name, ".odin") || strings.has_suffix(f.name, "_gen.odin") {
			continue
		}
		data, err := os.read_entire_file(fmt.tprintf("%s/%s", dir, f.name), context.temp_allocator)
		if err != nil {
			continue
		}
		text := string(data)
		for line in strings.split_lines_iterator(&text) {
			if strings.has_prefix(line, "package ") {
				return strings.trim_space(line[len("package "):]), true
			}
		}
	}
	fmt.eprintfln("build: %s: a key table beside no Odin package", dir)
	return "", false
}

// Expands every key table under KEY_ROOTS.
gen_keys :: proc(root: string) -> bool {
	for top in KEY_ROOTS {
		pkgs, err := os.read_directory_by_path(fmt.tprintf("%s/%s", root, top), -1, context.temp_allocator)
		if err != nil {
			continue
		}
		for p in pkgs {
			if p.type != .Directory {
				continue
			}
			dir := fmt.tprintf("%s/%s/%s", root, top, p.name)
			files, derr := os.read_directory_by_path(dir, -1, context.temp_allocator)
			if derr != nil {
				fmt.eprintfln("build: cannot read %s: %v", dir, derr)
				return false
			}
			for f in files {
				if f.type != .Regular || !strings.has_suffix(f.name, ".def") {
					continue
				}
				def := fmt.tprintf("%s/%s/%s", top, p.name, f.name)
				keys, is_table, ok := parse_keys(fmt.tprintf("%s/%s", root, def))
				if !ok {
					return false
				}
				if !is_table {
					continue // another kind of table (lib/p9's)
				}
				pkg := package_of(dir, files) or_return
				name := f.name[:len(f.name) - len(".def")]
				b := strings.builder_make(context.temp_allocator)
				fmt.sbprintfln(&b, "// Generated by ./build from %s. Do not edit.", def)
				fmt.sbprintln(&b)
				fmt.sbprintfln(&b, "package %s", pkg)
				fmt.sbprintln(&b)
				fmt.sbprintfln(&b, "// %s(6)'s keys, in %s's order: any other is refused (ndb.unknown_key).", name, def)
				fmt.sbprintln(&b, "@(rodata)")
				fmt.sbprintfln(&b, "%s_KEYS := [?]string{{", strings.to_upper(name, context.temp_allocator))
				for k in keys {
					fmt.sbprintfln(&b, "\t%q,", k)
				}
				fmt.sbprintln(&b, "}")
				out := fmt.tprintf("%s/%s_keys_gen.odin", dir, name)
				if old, rerr := os.read_entire_file(out, context.temp_allocator); rerr == nil && string(old) == string(b.buf[:]) {
					continue // rewritten only when it changes
				}
				if werr := os.write_entire_file(out, b.buf[:]); werr != nil {
					fmt.eprintfln("build: cannot write %s: %v", out, werr)
					return false
				}
				fmt.printfln("build: %s (%d keys)", out, len(keys))
			}
		}
	}
	return true
}

main :: proc() {
	// abi_gen.odin last: the ./build wrapper runs abigen again when a table
	// is newer than it.
	os.exit(gen_keys(".") && gen_abi(".") ? 0 : 1)
}
