// abigen: expands abi/vx/*.def into abi/vx/abi_gen.odin. The ./build wrapper
// runs it before compiling anything, the build tool included (which reaches
// abi:vx through lib/tar), whenever a table is newer than its output.
package abigen

import "core:fmt"
import "core:os"
import "core:strconv"
import "core:strings"

// One table, one truth: the ABI's lists live in abi/vx/*.def, and this file
// expands them into Odin. Nothing else generates code (ADR-0003).

Def_Entry :: struct {
	name:  string,
	value: string, // empty when the table's order gives the value
	line:  int,
}

// Reads the entries of one X-macro table: lines of the form MACRO(NAME) or
// MACRO(NAME, VALUE), with // comments and blank lines ignored.
parse_def :: proc(path, macro: string) -> (entries: [dynamic]Def_Entry, ok: bool) {
	data, err := os.read_entire_file(path, context.temp_allocator)
	if err != nil {
		fmt.eprintfln("build: cannot read %s: %v", path, err)
		return nil, false
	}
	entries = make([dynamic]Def_Entry, context.temp_allocator)
	text := string(data)
	line_no := 0
	for raw in strings.split_lines_iterator(&text) {
		line_no += 1
		line := raw
		if i := strings.index(line, "//"); i >= 0 {
			line = line[:i]
		}
		line = strings.trim_space(line)
		if line == "" {
			continue
		}
		if !strings.has_prefix(line, macro) || !strings.has_suffix(line, ")") || line[len(macro)] != '(' {
			fmt.eprintfln("%s:%d: expected %s(...)", path, line_no, macro)
			return nil, false
		}
		args := strings.split(line[len(macro) + 1:len(line) - 1], ",", context.temp_allocator)
		e := Def_Entry{name = strings.trim_space(args[0]), line = line_no}
		if e.name == "" {
			fmt.eprintfln("%s:%d: %s() has no name", path, line_no, macro)
			return nil, false
		}
		switch len(args) {
		case 1:
		case 2:
			e.value = strings.trim_space(args[1])
			if _, vok := strconv.parse_i64(e.value); !vok {
				fmt.eprintfln("%s:%d: value %q is not an integer", path, line_no, e.value)
				return nil, false
			}
		case:
			fmt.eprintfln("%s:%d: too many arguments", path, line_no)
			return nil, false
		}
		append(&entries, e)
	}
	return entries, true
}

// Odin's naming for a C table name: task_create -> Task_Create, ERR_NIL -> Err_Nil.
ada_case :: proc(name: string) -> string {
	return strings.to_ada_case(strings.to_lower(name, context.temp_allocator), context.temp_allocator)
}

// Generates abi/vx/abi_gen.odin from the three tables.
gen_abi :: proc(root: string) -> bool {
	syscalls := parse_def(fmt.tprintf("%s/abi/vx/syscalls.def", root), "VX_SYSCALL") or_return
	rights := parse_def(fmt.tprintf("%s/abi/vx/rights.def", root), "VX_RIGHT") or_return
	status_path := fmt.tprintf("%s/abi/vx/status.def", root)
	statuses := parse_def(status_path, "VX_STATUS") or_return

	b := strings.builder_make(context.temp_allocator)
	w := &b
	fmt.sbprintln(w, "// Generated by ./build from abi/vx/*.def. Do not edit.")
	fmt.sbprintln(w)
	fmt.sbprintln(w, "package vx")
	fmt.sbprintln(w)

	fmt.sbprintln(w, "// The syscall surface; the order gives the number.")
	fmt.sbprintln(w, "Syscall :: enum u32 {")
	for e in syscalls {
		fmt.sbprintfln(w, "\t%s,", ada_case(e.name))
	}
	fmt.sbprintln(w, "}")
	fmt.sbprintln(w)
	fmt.sbprintfln(w, "SYSCALL_COUNT :: %d", len(syscalls))
	fmt.sbprintln(w)
	fmt.sbprintln(w, "SYSCALL_NAMES := [Syscall]string{")
	for e in syscalls {
		fmt.sbprintfln(w, "\t.%s = %q,", ada_case(e.name), e.name)
	}
	fmt.sbprintln(w, "}")
	fmt.sbprintln(w)

	if len(rights) > 31 {
		// Bit 31 is VX_RIGHTS_SAME, handle_dup's "the rights the handle has".
		fmt.eprintfln("build: %d rights; at most 31 fit below VX_RIGHTS_SAME", len(rights))
		return false
	}
	fmt.sbprintln(w, "// Handle rights; the order gives the bit number.")
	fmt.sbprintln(w, "Right :: enum u32 {")
	for e in rights {
		fmt.sbprintfln(w, "\t%s,", ada_case(e.name))
	}
	fmt.sbprintln(w, "}")
	fmt.sbprintln(w)
	fmt.sbprintln(w, "Rights :: distinct bit_set[Right; u32]")
	fmt.sbprintln(w)

	fmt.sbprintln(w, "// Status codes: OK is zero and the only success; every error is negative.")
	fmt.sbprintln(w, "Status :: enum i32 {")
	for e in statuses {
		if e.value == "" {
			fmt.eprintfln("%s:%d: %s has no value", status_path, e.line, e.name)
			return false
		}
		fmt.sbprintfln(w, "\t%s = %s,", ada_case(e.name), e.value)
	}
	fmt.sbprintln(w, "}")

	out := fmt.tprintf("%s/abi/vx/abi_gen.odin", root)
	if err := os.write_entire_file(out, b.buf[:]); err != nil {
		fmt.eprintfln("build: cannot write %s: %v", out, err)
		return false
	}
	fmt.printfln("build: %s (%d syscalls, %d rights, %d statuses)", out, len(syscalls), len(rights), len(statuses))
	return true
}

main :: proc() {
	os.exit(gen_abi(".") ? 0 : 1)
}
